spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 13458264160
    url: jdbc:mysql://localhost:3306/art?characterEncoding=utf-8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    port: 6379
    host: 127.0.0.1
server:
  port: 8080